server:
  port: 7002
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

aws:
  ses:
    access-key: ${aws.ses.access-key}
    secret-key: ${aws.ses.secret-key}
    region: ap-northeast-2